### ISSUE TITLE
Allow for linear/date scales on line charts

### ISSUE THREAD

**Issue by npirlot** [datavisyn/chartjs-plugin-error-bars#10]
Hi,

Would you consider index-based errorBars data, rather than currently only supporting key based (even if you have tree models)?

I have a line chart, with a linear scale, where the labels are generated by using the Date() of the data row. This makes it impossible to use keys for the errorBars data.

I managed to get the plugin working as I needed by changing "`dataset.forEach((bar) => {`" to "`dataset.forEach((bar, ii) => {`" on [line 191](https://github.com/datavisyn/chartjs-plugin-error-bars/blob/master/src/plugin.js#L191), and then adding this after line 204:
`} else if (!hasLabelProperty && cur[ii]) {
	errorBarData = cur[ii];`

Thanks

**Comment by sluger** [comment]
Thanks for the suggestion. I'll have a look tomorrow or at the start of the next week.

**Comment by sgratzl** [comment]
can you give https://github.com/sgratzl/chartjs-chart-error-bars a try? it uses a different data structure
