### ISSUE TITLE
Error bars are not hidden when a dataset is disabled

### ISSUE THREAD

**Issue by luksal** [datavisyn/chartjs-plugin-error-bars#12]
This behavior is even visible in the test codepen: https://codepen.io/sluger/pen/YjJKYy
See the attached image
<img width="700" alt="im2" src="https://user-images.githubusercontent.com/9074730/60535078-957d7280-9d03-11e9-96f6-a4d358fb9ee8.png">

**Comment by samroberts707** [comment]
hey, has there been any progress with a patch for this?
