### ISSUE TITLE
Support for scatterplot?

### ISSUE THREAD

**Issue by agarbund** [datavisyn/chartjs-plugin-error-bars#17]
Thanks for developing this plugin, exactly what we needed! Is there a way to make this plugin work with [scatterplot](https://codepen.io/Marek-Fewtrell/pen/aypmGv) chart?

Possibly related to #10

**Comment by sgratzl** [comment]
hi, you could https://github.com/sgratzl/chartjs-chart-error-bars a try which supports scatterplots out of the box
