### ISSUE TITLE
data scaling

### ISSUE THREAD

**Issue by sgratzl** [datavisyn/chartjs-plugin-error-bars#2]
https://codepen.io/sgratzl/pen/PBLeJK?editors=0010

I don't understand how the error bars are scaled or defined. I define the value to be `50` and `plus: 20` and `minus: -30`

the result looks like that:

![image](https://user-images.githubusercontent.com/4129778/44030592-83622808-9f01-11e8-9e81-b480b7080d4d.png)

I would expect that the upper bar is at 70 and the lower at 20 assuming these are relative values to the base value. I cannot be percentage values either since it doesn't work out with `value=100` + 20% = 120 either.

**Comment by sgratzl** [comment]
turned out to be plus 20 **pixel** and minus 30 **pixel**

**Comment by bevand10** [comment]
Isn't that just wrong behaviour? I'd expect plus and minus values to be relative to the data unit, not rendering dimensions?

**Comment by sgratzl** [comment]
yes that's why I created the PR to fix that along with #1
