### ISSUE TITLE
Option to disable Error Bars via Javascript

### ISSUE THREAD

**Issue by luksal** [datavisyn/chartjs-plugin-error-bars#20]
It would be nice to have an option, which enables/disables the Error Bars via Javascript

**Comment by sgratzl** [comment]
can you give https://github.com/sgratzl/chartjs-chart-error-bars a try? it uses a different logic based on a separate chart type

**Comment by bigpresh** [comment]
For what it's worth, I've been able to add an option to hide the error bars by just poking at the chart:

```javascript
chart.data.datasets[0].errorBars = null;
chart.sensorChart.update();
```

It would be nice to be able to just toggle the visibility of the error bars separately rather than having to remove and restore the errorBars data, though.
