### ISSUE TITLE
Bug in accessing `chart.data.dataset[i]`

### ISSUE THREAD

**Issue by mbotsch** [datavisyn/chartjs-plugin-error-bars#21]
The current version of the master branch has a bug when accessing the dataset line 191 of `plugin.js`. This leads to errors on the console and does not show any error bars.

Please replace `chart.data.dataset[i]` by `chart.data.datasets[i]` to fix it. Or remove the whole if-clause from line 191 to line 196 (as done in develop branch).

**Comment by aevangeline** [comment]
Note : I made a PR for this  - #24
