### ISSUE TITLE
Error bars don't hide when hiding the actual chart.

### ISSUE THREAD

**Issue by a7mad7aydar** [datavisyn/chartjs-plugin-error-bars#25]
Hey Guys!

thanks for the library! it's amazing.
I noticed that when you click on the legend name to hide the chart, the bars still appear in the canvas. how to hide them?

here in your example, try to click on one of the legends to know what i mean. https://codepen.io/sluger/pen/YjJKYy

Thanks in advance!

**Comment by luksal** [comment]
Same as #12

**Comment by dave-driesmans** [comment]
Great library! Looking for a solution for this as well.
